//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "chores")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub title: String,
    pub description: Option<String>,
    pub household_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chore_tasks::Entity")]
    ChoreTasks,
    #[sea_orm(
        belongs_to = "super::households::Entity",
        from = "Column::HouseholdId",
        to = "super::households::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Households,
}

impl Related<super::chore_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChoreTasks.def()
    }
}

impl Related<super::households::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Households.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
