//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "chore_tasks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub description: String,
    pub chore_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chores::Entity",
        from = "Column::ChoreId",
        to = "super::chores::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Chores,
}

impl Related<super::chores::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chores.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
