//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "household_invite_codes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub code: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub household: Uuid,
    pub expiration: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::households::Entity",
        from = "Column::Household",
        to = "super::households::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Households,
}

impl Related<super::households::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Households.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
