//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::HouseholdType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "households")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub address_text: String,
    pub household_type: HouseholdType,
    #[sea_orm(column_type = "Float")]
    pub lat: f32,
    #[sea_orm(column_type = "Float")]
    pub lon: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::household_invite_codes::Entity")]
    HouseholdInviteCodes,
    #[sea_orm(has_many = "super::profiles::Entity")]
    Profiles,
}

impl Related<super::household_invite_codes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HouseholdInviteCodes.def()
    }
}

impl Related<super::profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Profiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
