//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::household_invite_codes::Entity as HouseholdInviteCodes;
pub use super::households::Entity as Households;
pub use super::profiles::Entity as Profiles;
