//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ToSchema)]
#[sea_orm(table_name = "profiles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub email: String,
    #[schema(value_type = String, format = "date-time")]
    pub created_at: DateTimeWithTimeZone,
    #[serde(skip_serializing)]
    #[schema(value_type = String, format = "date-time")]
    pub updated_at: DateTimeWithTimeZone,
    pub first_name: String,
    pub last_name: String,
    #[schema(value_type = Option<String>)]
    pub household_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::households::Entity",
        from = "Column::HouseholdId",
        to = "super::households::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Households,
}

impl Related<super::households::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Households.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
