//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "profiles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub email: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub first_name: String,
    pub last_name: String,
    pub household_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::households::Entity",
        from = "Column::HouseholdId",
        to = "super::households::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Households,
}

impl Related<super::households::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Households.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
