//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "household_type")]
pub enum HouseholdType {
    #[sea_orm(string_value = "family")]
    Family,
    #[sea_orm(string_value = "dorm")]
    Dorm,
    #[sea_orm(string_value = "other")]
    Other,
}
