// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu9BdZ_24ooHX-KAS8WMdCWzvGUTWzmOo',
    appId: '1:559207171465:android:3ac7cf5115fd78958b0d58',
    messagingSenderId: '559207171465',
    projectId: 'promillezone-v2',
    storageBucket: 'promillezone-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIoG4mh5vCnrkX0ZljeyWpmYQuY8HsQmw',
    appId: '1:559207171465:ios:f9cf2de2b00950008b0d58',
    messagingSenderId: '559207171465',
    projectId: 'promillezone-v2',
    storageBucket: 'promillezone-v2.firebasestorage.app',
    iosClientId: '559207171465-7ut8pa94mga0h09ini6lu3grji4b7llm.apps.googleusercontent.com',
    iosBundleId: 'com.example.promillezone',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSmX5ztvQF3zWPGlNpQVvkkXlpHeaED2w',
    appId: '1:559207171465:web:da0c185b30fb32108b0d58',
    messagingSenderId: '559207171465',
    projectId: 'promillezone-v2',
    authDomain: 'promillezone-v2.firebaseapp.com',
    storageBucket: 'promillezone-v2.firebasestorage.app',
    measurementId: 'G-859SYBP7BB',
  );

}